#!/usr/bin/node

const CMDjs = require('.');
const { log } = console;

const cmd = new CMDjs(
	{ '--help': _ => log('Help!') }
)

cmd.use({ '--ok': _ => log('ok') })
cmd.use('/home/mkr/Code/mkr/CMDjs/plugins')
log(cmd);
log(cmd.start(process));